import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import DesignerContextProvider from "@/components/context/DesignerContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='w-full h-screen'>
          <DesignerContextProvider>
            {children}
          </DesignerContextProvider>
      </body>
      {/* <body className={inter.className}>{children}</body> */}
    </html>
  )
}
